name: Rust Checks

on: [push, pull_request]

jobs:
  cargofmt:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: fmt
        run: cargo fmt -- --check

  clippy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: clippy without CUDA
        run: cargo clippy --no-default-features -- -D warnings --verbose
